### ISSUE TITLE
Focus lock will be lost when using DatePicker inside a modal window

### ISSUE THREAD

**Issue by semgey** [semrush/intergalactic#1004]
**Describe the bug**
Focus lock will be lost when using DatePicker inside a modal window
Also, if there is no focus lock, it is impossible to reach the Today button from the keyboard

**Code example**
Open [codesadnbox](https://codesandbox.io/p/sandbox/romantic-sun-ycwcmm?file=%2Fsrc%2FApp.tsx%3A17%2C11).

**To Reproduce**
1. Set focus on DatePicker.Trigger
2. Press Tab
3. See error

**Interesting**
1. Set focus on DatePicker.Trigger
2. Quickly press Tab twice
3. See regular focus-lock

**Comment by msereniti** [comment]
Hi, the provided codesnadbox looks unavailable.

Could you please recreate it?

I've tried to reproduce the unexpected behavior with

```tsx
import React from 'react';
import { DatePicker } from '@semcore/ui/date-picker';
import Button from '@semcore/ui/button';
import Modal from '@semcore/ui/modal';

const Demo = () => {
  const [visible, setVisible] = React.useState(false);
  const handleOpen = React.useCallback(() => setVisible(true), []);
  const handleClose = React.useCallback(() => setVisible(false), []);

  return (
    <React.Fragment>
      <Button onClick={handleOpen}>Open modal</Button>
      <Modal visible={visible} onClose={handleClose}>
        <DatePicker>
          <DatePicker.Trigger />
          <DatePicker.Popper />
        </DatePicker>
      </Modal>
    </React.Fragment>
  );
};

export default Demo;
```

But everything looks fine

**Comment by msereniti** [comment]
Closing as non reproducible. Do not hesitate to reopen it with a bug-containing example
