### ISSUE TITLE
DropdownMenu doesn't keep focus on the Button trigger

### ISSUE THREAD

**Issue by shvedovskiy** [semrush/intergalactic#1018]
**Code example**
https://codesandbox.io/p/sandbox/determined-black-d866ry

**To Reproduce**
Steps to reproduce the behavior (all actions should be performed using the keyboard):
1. Open first dropdown
2. Navigate to dropdown item and click on it. A modal window should appear.
3. Close modal. Dropdown is closed, the focus returns to the trigger.
4. Tab to second dropdown and open it.
5. Navigate to dropdown item and click on it. A modal window should appear.
6. Close modal. Dropdown is closed, but focus doesn't return to the trigger.

**Expected behavior**
Both dropdown triggers retain focus after closing the menu.

**Additional context**
This seems to be due to the fact that DropdownMenu controls focus differently depending on which component is passed as the trigger. For example, if we open the dropdown menu and navigate through its elements, then in case of `ButtonTrigger` (step 2), the focus remains on it, and in case of `Button` (step 5), the focus disappears.

**Comment by msereniti** [comment]
Hi @shvedovskiy, the provided example doesn't have any modals inside. Could you updated it?

**Comment by msereniti** [comment]
Seems like our recent dropdowns update fixed the issue. It was reproducible two days ago but not it's not.
