### ISSUE TITLE
[checkbox] Visual bug on dark theme 🖤

### ISSUE THREAD

**Issue by lsroman** [semrush/intergalactic#1193]
Here the option with "I'm option-checkbox" is not selected, but it looks active(

<img width="439" alt="Снимок экрана 2024-03-12 в 16 44 02" src="https://github.com/semrush/intergalactic/assets/4582799/9c78fd5e-1653-4b87-85cf-9450a5fe3fba">

**To Reproduce**
1. Go to [docs](https://developer.semrush.com/intergalactic/components/select/select-code#options)
2. Click on Option with checkbox

**Expected behavior**
Checkbox should not have a chevron

**Comment by j-mnizhek** [comment]
Thnak you Romaaaa for bringing this! We actually have no dark theme for the components yet, that's why there are can be some inconsistencies for components' styles in dark theme.
