### ISSUE TITLE
Select.Option.Checkbox visual glitch

### ISSUE THREAD

**Issue by Evalon** [semrush/intergalactic#1212]
**Describe the bug**
The checkbox is visually not selected when using `<StrictMode>` to check that the code aligns to double renders and other things.
It reliably happens in more complex production code.

**Code example**
Open [codesandbox](https://codesandbox.io/p/sandbox/quizzical-pond-vs6pqp?file=%2Fsrc%2FApp.tsx%3A47%2C43)

**To Reproduce**
1. Open the example and make sure that `<StrictMode>` is active
2. Click on an option
3. The checkbox is not selected, but the option is selected.

**Expected behavior**
Option and checkbox are selected.

**Additional context**
The root cause is because of impure render [here](https://github.com/semrush/intergalactic/blob/master/semcore/select/src/Select.jsx#L173-L174)

**Comment by msereniti** [comment]
<img width="693" alt="Screenshot 2024-03-18 at 12 46 25" src="https://github.com/semrush/intergalactic/assets/31261408/3de0d336-a87e-4dfc-a9ac-bd2e94f1155f">

Hi, could you please update sandbox access?

**Comment by Evalon** [comment]
Updated

**Comment by msereniti** [comment]
See it, will fix asap
