### ISSUE TITLE
Extended TypeScript props for components

### ISSUE THREAD

**Issue by freeyoungstrong** [semrush/intergalactic#1344]
**Is your feature request related to a problem? Please describe.**
I would like to have the ability to import extended TypeScript props. For instance, I intend to develop my own Link component, which should be built upon your existing Link component. Specifically, for my custom Link component, I wish to inherit all TypeScript props available in your Link component. Essentially, I want the LinkProps to include all the properties from the `a` tag, such as `href`, `onClick`, and so on. This applies to all components, not just Link.

**Describe the solution you'd like**
Props of all components should have default HTML props from the tags on which they are created.

**Additional context**
I have code like this:
```
import SemcoreLink, { LinkProps } from '@semcore/ui/link';
...
export const Link = (props: LinkProps) => {
  const { children, href } = props;
  ...
 };
```
And now I have ts error:
<img width="620" alt="Screenshot 2024-05-07 at 13 53 46" src="https://github.com/semrush/intergalactic/assets/44463016/303c1553-89d7-4829-9be0-a600683c2433">

**Comment by msereniti** [comment]
Take a look onto this documentation article. It will help you to make a custom Link component with correct typings.
https://developer.semrush.com/intergalactic/core-principles/writing-code/wrapping-components
