### ISSUE TITLE
Incorrect signature of onDisplayedPeriodChange method in MonthRangePicker

### ISSUE THREAD

**Issue by pasdechlopez** [semrush/intergalactic#259]
"@semcore/date-picker": "2.7.1".

Hello! I've encountered incorrect signature in onDisplayedPeriodChange method in MonthRangePicker. See details on screenshots. Long story short, onDisplayedPeriodChange may return argument of type Date or string (date: Date | string), when it must be Date type only (date: Date) according to method's signature. 

<img width="1059" alt="Screenshot 2022-06-02 at 14 14 04" src="https://user-images.githubusercontent.com/53097163/171617459-adeae4ee-921e-472b-9cb7-6e1929065552.png">
<img width="801" alt="Screenshot 2022-06-02 at 13 51 44" src="https://user-images.githubusercontent.com/53097163/171617514-66381992-b6c9-44a8-96bf-403269a33d86.png">

<img width="932" alt="Screenshot 2022-06-02 at 14 15 06" src="https://user-images.githubusercontent.com/53097163/171617562-a8d916cf-10c3-4176-9481-bae6daeb9209.png">

**Comment by phytonmk** [comment]
Hi Daniil,

thank you for your bug report!

Property signature is correct, `onDisplayedPeriodChange` should only be fired with `Date` object. Mentioned string type is unexpected.  I've tried to reproduce that issue on my own DatePicker examples and inspected source code for possible errors but for me everything works well.

Could you please provide minimal reproducible example (e.g. on codesandbox)?
