### ISSUE TITLE
Global theme doesn't work

### ISSUE THREAD

**Issue by inthedark122** [semrush/intergalactic#467]
I have made a simple demo on the code sandbox

https://codesandbox.io/s/semrush-theme-3kbhtd?file=/webpack.config.js

I followed by documentation https://developer.semrush.com/intergalactic/style/themes/themes-global/

But I don't see that button changed to a red color. You can check the file: `src/theme/button/button.shadow.css`

Can you help me to change global styles for any elements?

---

I started my local project with Vite
My local config is:

- vite: `^2.9.9`
- @semcore/ui: `^13.2.0`
- @semcore/babel-plugin-react-semcore: `4.3.0`

**vite.config.ts:**
```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig(() => {
  const config = {
    plugins: [react({
      babel: {
        configFile: true,
      }
    })]
  }


  return config;
});

```

**babel.config.js:**

```
const path = require('path');

const presets = [];
const plugins = [
  [
    '@semcore/babel-plugin-react-semcore',
    {
      theme: path.resolve(process.cwd(), 'src', 'theme'),
      verbose: true,
    },
  ],
];

module.exports = { presets, plugins };
```

**Comment by inthedark122** [comment]
I made an example of a project: https://github.com/inthedark122/vite-semrush-theme

# Check the branches:

## master

just two buttons with the default theme

##  theme-local 

I added a library for the local theme `@semcore/babel-plugin-styles` and applied them to my custom button component.

It works perfectly and doesn't have any issue

## theme-global

- I added a library for the global theme `@semcore/babel-plugin-react-semcore`.
- Made `theme` folder in the `src` folder
- Set up the folder in the babel config

# But I have the issues:

- [ ]  I should add `@semcore/babel-plugin-styles` to apply local config
- [ ]  I don't see any changes in my Button styles

**Comment by lsroman** [comment]
It definitely works with webpack. Here is my example [theme.zip](https://github.com/semrush/intergalactic/files/10186667/theme.zip)

`webpack.config.js` is not processed in codesandbox. You can verify this if you delete this file.

**Comment by lsroman** [comment]
https://github.com/lsroman/vite-semrush-theme/blob/theme-global/vite.config.ts
I forked your project and changed the config. Honestly I don't know why babel is not worked in `@vitejs/plugin-react`. But the themes work fine through the `vite-plugin-babel`.
<img width="212" alt="Screenshot 2022-12-08 at 17 41 14" src="https://user-images.githubusercontent.com/4582799/206490332-26eb2254-9849-4497-a12d-6318c32f5c90.png">

**Comment by lsroman** [comment]
If you have no more problems, then close the issue ☺️
