### ISSUE TITLE
Small layout bug for dynamically imported module

### ISSUE THREAD

**Issue by PavelKoroteev** [semrush/intergalactic#468]
https://user-images.githubusercontent.com/34572116/205624207-2aa65c24-51eb-4469-bd0a-34247a9351b5.mov

**Comment by lsroman** [comment]
Thank you.
This error appeared during site deployment. I fixed it by [reloading the page](https://github.com/semrush/intergalactic/commit/18d6fd4e5d10873c0339f907daeb5c2b34917dc1).
