### ISSUE TITLE
FormatText component does not support lists's numeration-related attributes

### ISSUE THREAD

**Issue by dpodolkhov** [semrush/intergalactic#685]
## Motivation

HTML OL element has 'start' and 'reversed' attributes that impacts items' markers.

The native HTML code like this should render an item started with "3".
```
    <ol start="3">
        <li> this item starts with "3" </li>
    </ol>
```

At the same time, wrapping lists with FormatText breaks this features
```
<FormatText>
    <ol start="3">
        <li> this item starts with "1" </li>
    </ol>
</FormatText/>
```

Looking into source code it is clear why this happens:
- styles for FormatText [reset](https://github.com/semrush/intergalactic/blob/master/semcore/format-text/src/style/format-text.shadow.css#L74) standard list markers and [puts own markers](https://github.com/semrush/intergalactic/blob/master/semcore/format-text/src/style/format-text.shadow.css#L95) based on custom counter 'item'. That counter obviously starts from 0 and does not depend on any HTML attributes.

## Proposal:

Replace custom counter 'item' with [built-in counter 'list-item'](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_counter_styles/Using_CSS_counters). This built-in counter is automatically initiated by OL tag and supports OL's attributes.

## How to test:

This code should render an item starting with "3"
```
<FormatText>
    <ol start="3">
        <li> this item starts with "3" </li>
    </ol>
</FormatText/>
```

**Comment by msereniti** [comment]
Changes proposed in the pull request were very reasonable https://github.com/semrush/intergalactic/pull/682/files but would cause a breaking changes in the format-text component.

Now I am looking to either create a new component that will be a replacement for format-text (for example, to name it `article` or something like that) or add boolean prop that toggles FormatText behavior.

First option example (`FormatText` to be deprecated):
```jsx
<Article>
  <ol start="3">
    <li> this item starts with "3" </li>
  </ol>
</Article>
```

Second option example: 
```jsx
<FormatText nativeLists>
  <ol start="3">
    <li> this item starts with "3" </li>
  </ol>
</FormatText >
```

@dpodolkhov @dshashkov-semrush, what option looks more preferable for you?

**Comment by dpodolkhov** [comment]
As for me, this issues is a bug-fix, because it contributes to component's main goal -- show inner HTML in a most native way.
I would definitely not like additional props to make a component do what is should do. 
So I'd prefer keeping it as FormatText, probably with major version up (renaming is actually the same thing).

**Comment by msereniti** [comment]
Seems you are not caring about other developers who use the components – I can't do same. In the recent release I've published css changes that disables all non-default counters if `start`, `reserved` or `type` arguments are provided to the `ol` or `ul`.

Now you can use these attributes.

**Comment by dshashkov-semrush** [comment]
I agree that it seems like there is an issue with the current component's functionality. According to its description, it is "[A wrapper component required to add styles to native tags](https://developer.semrush.com/intergalactic/style/typography/typography-api/#formattext)".

Therefore, I believe the best solution is to fix the issue with styles 🤷 


P.S. There is [another issue](https://codesandbox.io/s/vibrant-panini-z9tr9s?file=/src/App.tsx) with \<ol\> list styles: at large numbers, the numbering begins to overlap the content of the list element itself. Do I need to report it separately?
