### ISSUE TITLE
The FormatText component does not support native attributes for the <ol> tag

### ISSUE THREAD

**Issue by dshashkov-semrush** [semrush/intergalactic#703]
**Describe the bug**
The FormatText component does not allow "reversed", "start" and "type" [attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol#attributes) to be used with the \<ol\> tag.

**Code example**
[Codesandbox](https://codesandbox.io/s/wizardly-bush-x2qcpr?file=/src/App.tsx).

**Expected behavior**
I expect the correct behavior of the \<ol\> tag when using its native attributes.

**Comment by msereniti** [comment]
Will keep discuss in the [first one](https://github.com/semrush/intergalactic/issues/685)
