### ISSUE TITLE
Missing transition-duration on ProgressBar.Value

### ISSUE THREAD

**Issue by kirilldronkin** [semrush/intergalactic#714]
**Describe the bug**
Looks like it was accidentally removed [here](https://github.com/semrush/intergalactic/commit/aa43462a149a57306bd405efe84cf505c1073c54#diff-77acfb41ea17288f5624600a907b970e8e402da45072e098aacede13c8ded6bcL23), so the fixes weren't such safe I suppose ;D

**Comment by msereniti** [comment]
Hi, the issue was just fixed!
https://github.com/semrush/intergalactic/releases/tag/v15.10.0
