### ISSUE TITLE
Ability to change coordinates in <Donut.Label/>

### ISSUE THREAD

**Issue by grismego** [semrush/intergalactic#715]
**Problem:**
When I pass ```foreignObject``` as a tag, Label is not positioned correctly.  Passing the coordinates doesn't change anything because they are not changeable. [Code](https://github.com/semrush/intergalactic/blob/master/semcore/d3-chart/src/Donut.jsx#L374)

**Example:**
I've prepared an example https://codesandbox.io/s/silly-scott-9kqpz2?file=/src/App.tsx

**Comment by msereniti** [comment]
Hi, it was fixed in the latest release, now you can set `x` and `y`

https://github.com/semrush/intergalactic/releases/tag/v15.11.1
