### ISSUE TITLE
Error when rendering zero pies of Donut chart

### ISSUE THREAD

**Issue by shvedovskiy** [semrush/intergalactic#730]
#### Describe the issue

I've upgraded to `@semcore/ui@15.13.0` (`@semcore/d3-chart@3.10.0`) and I'm trying to draw a donut of two segments:

```jsx
import { colors, Donut, Plot } from '@semcore/ui/d3-chart';

const chartData = {
    value,
    other: 100 - value,
};

<Plot width={24} height={24} data={chartData}>
    <Donut outerRadius={12} innerRadius={7} duration={0}>
        <Donut.Pie dataKey='value' />
        <Donut.Pie dataKey='other' color={colors['gray-200']} />
    </Donut>
</Plot>
```

However, when the `other` value is zero, the rendering of graph is interrupted by the following error:

`Uncaught Error: Pie(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`

#### Code example

https://codesandbox.io/s/elastic-breeze-k4xg3d

In this example, the error is not reproduced 🤷🏻, perhaps it's somehow related to the webpack's specific behaviour.

**Comment by msereniti** [comment]
Hi,
I have created a vite project with `pnpm create vite`, added `@semcore/ui` with `pnpm add @semcore/ui`, replaced app component code with code from the codesandbox – it worked.
I also created a create-react-app project with `npx create-react-app my-app`, added `@semcore/ui` with `npm install @semcore/ui`, replaced app component code with code from the codesandbox – it worked.

Could you please provide me more information about how to reproduce the issue?

**Comment by msereniti** [comment]
Reopen issue please when you will reproduce bug again and will be able to provide more info about reproducing it!
