### ISSUE TITLE
[Typography] Add semibold prop to the Text component

### ISSUE THREAD

**Issue by j-mnizhek** [semrush/intergalactic#733]
**Is your feature request related to a problem? Please describe.**
Props for our Text component lacks `semibold` prop with value 600. It's necessary for using in titles.
<img width="904" alt="image" src="https://github.com/semrush/intergalactic/assets/77798437/224987ed-304c-4f29-a8bd-f92f82e34a7d">

**Describe the solution you'd like**
Add a `semibold` prop with 600 value to the API of the Text component.

**Comment by msereniti** [comment]
Prop was added in the latest release https://github.com/semrush/intergalactic/releases/tag/v15.15.0
