### ISSUE TITLE
Error when rendering zero pie of Donut chart

### ISSUE THREAD

**Issue by shvedovskiy** [semrush/intergalactic#735]
**Describe the bug**
The rendering of donut with zero value segment is interrupted by the following error:
```
Uncaught Error: Pie(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
```

**Code example**
[Codesandbox](https://codesandbox.io/s/runtime-surf-m57sfv?file=/src/App.tsx). This bug doesn't appear on React <18.

**Expected behavior**
In React 16 there is no error when displaying the zero pie.

**Additional context**

It looks like the error is being caused by this return expression, since React <18 doesn't support `return undefined`: https://github.com/semrush/intergalactic/blob/a47a5b3c9acb53d7a693784de4347801618a5119/semcore/d3-chart/src/Donut.jsx#L348

Versions:
- `@semcore/ui@15.14.0`
- `@semcore/d3-chart@3.10.0`
- `react@16.14.0`

**Comment by msereniti** [comment]
The issue was fixed in the latest release https://github.com/semrush/intergalactic/releases/tag/v15.15.0 🦾
