### ISSUE TITLE
DatePicker.InputTrigger Alignment Issue Caused by CSS line-height Setting

### ISSUE THREAD

**Issue by denis-pakhorukov** [semrush/intergalactic#743]
**Describe the bug**
Changing the line-height CSS property _outside_ the DatePicker component causes alignment issues _inside_ the component when using DatePicker.InputTrigger.

**Code example**
Open [codesandbox](https://codesandbox.io/s/lucid-night-glln2t?file=/src/App.tsx).

**To Reproduce**
1. Wrap a DatePicker (with the default DatePicker.InputTrigger) into a div.
2. Set the div's line-height to 2.
3. See that DatePicker.InputTrigger is distorted when displaying the humanized date.

**Expected behavior**
DatePicker.InputTrigger remains unaffected by changes to the line-height property. It displays the humanized date with proper alignment, similar to DatePicker.ButtonTrigger.

**Comment by msereniti** [comment]
Hi, thank you fro the reporting!

Line height was enforced in the latest release. Now the component doesn't visually breaks in case of non `normal` line height.

https://github.com/semrush/intergalactic/releases/tag/v15.19.0
