### ISSUE TITLE
Use VitePress as a documentation engine

### ISSUE THREAD

**Issue by msereniti** [semrush/intergalactic#744]
Our current documentation website contains a lot of home-invented wheels that makes it's support extremely hard. Also it doesn't have good browsers support and loads pretty slow. 

Recently https://vitepress.dev/ got out of alpha testing. It should be pretty good for us. 

Possible troubles:
1. It uses Vue, so we will get a few .vue files in the repository.
2. It doesn't have built-in code sandboxes. Need to implement it by ourself.
3. Design is pretty far from the design system. Need to kinda of merge it.

**Comment by j-mnizhek** [comment]
Seems that we can already close this issue 🥳
There are some things to update in the future, but the overall migration looks done.
