### ISSUE TITLE
Undo / Redo icons implementation doesn't match the design in Figma

### ISSUE THREAD

**Issue by denis-pakhorukov** [semrush/intergalactic#766]
Actual result

![image](https://github.com/semrush/intergalactic/assets/41336408/82641eab-17d5-4c8d-9e45-3e1cc346166c)

Expected result

![image](https://github.com/semrush/intergalactic/assets/41336408/afc52b70-9972-49fd-9161-4b0496019881)

**Comment by denis-pakhorukov** [comment]
Sorry for posting without a proper explanation. I meant that the implementation doesn't match figma.

Figma: https://www.figma.com/file/4jExUwn0abTGDvrXndPEeI/Semrush---Icons-Library-(Community)?type=design&node-id=2502-244&mode=design&t=NNDh97dRh1c6DAvN-4

Implementation
![image](https://github.com/semrush/intergalactic/assets/41336408/0e337f87-fd8f-4ccb-8aba-05fff9e84cca)

**Comment by j-mnizhek** [comment]
OMG! Thank you for bringing this! I'll see what could go wrong with them.

**Comment by j-mnizhek** [comment]
I know what had go wrong with it. Former designer redesigned it, but forgot to push it to the library. I'll commit it tomorrow!

**Comment by denis-pakhorukov** [comment]
Hi team,

if you could take a look at this today, it would be highly appreciated.

Thank you!

**Comment by j-mnizhek** [comment]
@denis-pakhorukov Sure! I'll try to find time today to update the icons.

**Comment by j-mnizhek** [comment]
Updated both `Undo` and `Redo` icons in this PR https://github.com/semrush/intergalactic/pull/778.
But I guess it will be merged as soon as guys will come back from PTO's (on Thursday).

**Comment by j-mnizhek** [comment]
Updated icons was added in the Icons's 4.10.0 version.
