### ISSUE TITLE
Add `display` property to BoxProps

### ISSUE THREAD

**Issue by dpodolkhov** [semrush/intergalactic#800]
The often need is to make some inline-* component to be block (tooltips around form controls, sketelons, etc). 
(There are more than dozen places with `style={{ display: 'block' }}` properties throughout my project.)

BoxProps interface has `inline` prop, which can only be set to true. 

I'd like to request to add a `display` prop to BoxProps, just like `position`.

**Comment by ilyabrower** [comment]
We added this prop in #810
