### ISSUE TITLE
The focus ring remains on the previous element.

### ISSUE THREAD

**Issue by Aleksei2212** [semrush/intergalactic#815]
**Describe the bug**
The focus ring remains on the element when switching focus to the next interactive element.

<img width="372" alt="image" src="https://github.com/semrush/intergalactic/assets/142894895/18fb81ac-6670-46d1-8023-88c2c6b54088">

**Code example**
Open [codesandbox](https://codesandbox.io/s/friendly-robinson-myxl4g?file=/src/App.tsx).

**To Reproduce**
1. Set focus on the Next button. 
2. Press "Enter" on it.
3. Wait for the loading.
4. Press "Tab" to move to the next interactive element.
5. See two focus rings. 

**Expected behavior**
When transitioning to the next interactive element, the focus ring should only be on it.

**Actual behavior**
When transitioning to the next interactive element, the focus ring remains on both the previous and current elements.

**Comment by Aleksei2212** [comment]
Team, this bug is still reproducible. Version @semcore/ui 15.28.0.

**Comment by Aleksei2212** [comment]
The main problem is that the focus ring remains on the element when it is out of focus.

Steps to reproduce the behavior:

1. Open [codesandbox](https://codesandbox.io/s/friendly-robinson-myxl4g?file=/src/App.tsx).
2. Use the keyboard to focus on the "Next" button
3. Press Enter.
4. After the start of the loading process, the button becomes disabled, and the focus ring disappears (**this is ok**).
5. After the loading is complete, the focus ring appears on the button (**this is also ok**).
6. Press Shift+Tab to shift the focus to the "Prev" button.
7. Press Enter.
8. You will notice that the focus ring has appeared on the "Prev" button and remains on the "Next" button - **This is not okay**.
9. Press Shift+Tab again. The focus ring appears on the "<<" button but still remains on "Prev" and "Next."


In total, we have 3 focus rings instead of one.


See the video:

https://github.com/semrush/intergalactic/assets/142894895/63bb921e-e4d9-4e53-9f97-407a1979bce9

**Comment by ilyabrower** [comment]
Thank you for `codesandbox`, it helped to find the problem.
