### ISSUE TITLE
InlineEdit autoFocus onConfirmHandler instant call

### ISSUE THREAD

**Issue by Evalon** [semrush/intergalactic#822]
**Describe the bug**
OnBlur event wrong logic with autoFocus and dropdown menu

**Code example**
[codesandbox](https://codesandbox.io/s/zen-sound-yfhrnc?file=/src/App.tsx)

**To Reproduce**
1. Click on dropdown menu
2. Click rename
3. See that onConfirmHandler called instantly

**Comment by msereniti** [comment]
Thank you for reporting!
The issue was fixed in the latest release

https://github.com/semrush/intergalactic/releases/tag/v15.28.1
