### ISSUE TITLE
Feature Popover is displayed on top of the Modal overlay

### ISSUE THREAD

**Issue by heckowl** [semrush/intergalactic#826]
**Describe the bug**
When you click on the button to open the Modal window, the Feature Popover will be displayed above the overlay.

**Code example**
Open [codesandbox](https://codesandbox.io/s/stupefied-pascal-mktfm8?file=/src/App.tsx)

**To Reproduce**
1. Click on Open modal button
2. See error

**Expected behavior**
Feature Popover is displayed under the Modal overlay.

**Additional context**
z-index values:
-  z-index: var(--intergalactic-z-index-popper, 700);
-  z-index: var(--intergalactic-z-index-modal, 600);

**Comment by msereniti** [comment]
Hi, basically it's an intended behavior that ensures that feature popover may be displayed over the modals.

You need to close all possible feature popovers while opening new modals.
