### ISSUE TITLE
Components for use small charts for trends and scores views

### ISSUE THREAD

**Issue by ilyabrower** [semrush/intergalactic#850]
**Is your feature request related to a problem? Please describe.**
We want to show some data about trends or scores with charts, but it should be simple view, without many special features (like axis, many lines, a11y, etc). For example:
<img width="278" alt="Screenshot 2023-10-31 at 08 37 32" src="https://github.com/semrush/intergalactic/assets/8787452/56c11e7f-2d1d-440f-bc61-3f35ae108faf">
<img width="270" alt="Screenshot 2023-10-31 at 08 37 39" src="https://github.com/semrush/intergalactic/assets/8787452/ac092f3f-b30f-44d6-a552-4ceade77b2c2">
<img width="130" alt="Screenshot 2023-10-31 at 08 37 59" src="https://github.com/semrush/intergalactic/assets/8787452/46a0de84-c83d-4ac7-a1b3-e3df6441aac8">

**Describe the solution you'd like**
It could be two components:
- Score. The component for render some value (usually in percents) with one of two simple charts - Donut or Radar.
- Trend. The component for render a list of values on the Line or Bar chart.

**Describe alternatives you've considered**

**Additional context**

**Comment by j-mnizhek** [comment]
**More details on this**

Product teams have a need to add a component for simple visualization of trends or values. I currently refer to this component as MiniChart, but it's name is still open for discussion.

**What this component needs:**

- [ ] Ability to choose the type of visualization: a trend or value.

![Image](https://github.com/semrush/intergalactic/assets/77798437/e7b4106e-c11c-4036-ab31-89d370c3a5c9)

- [ ] Ability to set the SVG size. Find default SVG sizes in the [branch of Figma Charts library](https://www.figma.com/file/eODzGSSSlI8fl0x5fsv9cf/branch/J43hB38zrgzx3cfwo237A3/%E2%9C%A8-Charts?type=design&node-id=34-48135&mode=design&t=1jxm3NSdTuuMJIgT-11).

- [ ] Customization options for the last element in the Line chart and a customizable element in the Bar chart. Customization here refers to the color.

![Image](https://github.com/semrush/intergalactic/assets/77798437/3a34e690-9104-474d-a411-0d32f5245a99)
![Image](https://github.com/semrush/intergalactic/assets/77798437/b1d85580-20ae-4f12-ac9a-9ceec954cf93)

- [ ] Add animation for the appearance of charts (similar to the animation used in our larger charts).

- [ ] Integrate the ability to display a tooltip for this visualization. The tooltip should display all data related to the chart. Can we add a value name inside tooltip for such a visualization?

- [ ] A discussable question: Should we include a skeleton inside this component or not? [There are patterns for chart skeletons available](https://www.figma.com/file/l461PgAqj1I1APFUOUBE8x/Skeleton-patterns?type=design&node-id=1-37&mode=design&t=QAsGgsEFGEC5EAg8-11), and they can be reused for smaller charts.

**Comment by j-mnizhek** [comment]
I removed point for adding tooltip from the requirements to this component, because usually this component is wrapped into tooltip with some other elements like value, link, etc.
