### ISSUE TITLE
Pagination input doesn't display Return icon in border-box context

### ISSUE THREAD

**Issue by shvedovskiy** [semrush/intergalactic#863]
**Describe the bug**
Inside our product, we forcibly enable an border-box context mode, but this leads to problems displaying the pagination component: the Return icon that should appear when focusing on the page input field isn't displayed. Maybe there's a way not to rely on content-box mode in the component markup?

**Code example**
https://codesandbox.io/s/eloquent-bird-v6tcpl

**To Reproduce**
1. Click/focus on page input
2. Make sure that Return icon doesn't appear:
<img width="339" alt="Screenshot 2023-11-06 at 18 32 58" src="https://github.com/semrush/intergalactic/assets/5951118/8facc34a-e9db-4886-8164-4d34a928e8a5">

**Expected behavior**
The Return icon is displayed.

**Comment by ilyabrower** [comment]
Hi! I'm not sure, that this is a bug.
This is happen, because in `box-sizing: border-box;` width is including paddings (in our case width is 16px and paddings by default are - 8px). So, 16-8*2 = 0 - and you don't have a place for the content (icon).

Let me ask you - why do you use `box-sizing: border-box;` for all elements? 
Because by default in the [CSS box model](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_box_model/Introduction_to_the_CSS_box_model), the width and height you assign to an element is applied only to the element's content box.

**Comment by ilyabrower** [comment]
But if you use our components in your app, your selector (because of id) will be always more specific then ours. 
Could you maybe change your selector from id to class?

Another way - write something like that:
```
import React from "react";
import Pagination from "@semcore/ui/pagination";
import Return from "@semcore/ui/icon/Return/m";

const Demo = () => {
  const totalPages = 122360;
  return (
    <Pagination totalPages={totalPages}>
      <>
        {totalPages === 1 ? null : (
          <>
            <Pagination.FirstPage />
            <Pagination.PrevPage />
            <Pagination.NextPage />
          </>
        )}
        <Pagination.PageInput>
          <Pagination.PageInput.Value />
          <Pagination.PageInput.Addon
            tag={Return}
            interactive
            aria-label={"confirm"}
            style={{ boxSizing: "content-box" }} // <- set correct style here
          />
        </Pagination.PageInput>
        <Pagination.TotalPages />
      </>
    </Pagination>
  );
};
```

**Comment by shvedovskiy** [comment]
Okay, I have the possibility to replace the our selector from the id to the class to fix the specificity, but our application CSS are inserted later than the Uikit CSS, so it still have a higher priority. Anyway, manual overriding `<Pagination.PageInput.Addon />` styles to `content-box` solves the problem, thank you!
