### ISSUE TITLE
Fixed header doesn't work in the table inside the Spin container

### ISSUE THREAD

**Issue by shvedovskiy** [semrush/intergalactic#899]
**Describe the bug**
When placing Data table inside the Spin container, the table header fixation breaks.

**Code example**
https://codesandbox.io/s/relaxed-bash-jz6yck

**To Reproduce**
1. Open example
2. Scroll page down
3. Make sure that the table header is hidden

**Expected behavior**
When scrolling, the table title sticks to the top of the screen.

**Comment by ilyabrower** [comment]
Hi! It doesn't seems like a bug... Spin Container have `overflow: hidden;`, so you shouldn't expect that content in it will scroll.

Could you rewrite your render like this?
```
return loading ? <SpinContainer loading={loading} size="l" h={600}/> : (
     <DataTable data={data}>
        <Box position="sticky" top={0} zIndex={2}>
          <DataTable.Head>
            ...
          </DataTable.Head>
        </Box>
        <DataTable.Body />
      </DataTable>
);
```

And if you need to limit a height of table container, could you show me more information about your case?

**Comment by shvedovskiy** [comment]
Hi Ilya! Okay, I can really just render SpinContainer separately without wrapping the entire table in it. Thank you!
