### ISSUE TITLE
Getting an error from VS code for Checkbox onChange.

### ISSUE THREAD

**Issue by tomhornyak** [semrush/intergalactic#976]
Using the demo code on https://developer.semrush.com/intergalactic/components/checkbox/checkbox-code,
nothing is rendered.
onChange is flagged with an error

Type '(value: boolean) => void' is not assignable to type 'FormEventHandler<HTMLLabelElement>'.
  Types of parameters 'value' and 'event' are incompatible.
    Type 'FormEvent<HTMLLabelElement>' is not assignable to type 'boolean'.ts(2322)
index.d.ts(1451, 9): The expected type comes from property 'onChange' which is declared here on type 'IntrinsicAttributes & { tag?: "label" | undefined; children?: ComponentChildren<Omit<CheckboxProps, "children"> & { children: ReactNode; }, CheckboxContext, ReturnResult, never[]>; } & ComponentBasicProps<...> & { ...; } & Omit<...>'
(property) onChange?: React.FormEventHandler<HTMLLabelElement> | undefined

``

**Comment by ilyabrower** [comment]
Hi! I need more information. What is your version of typescript and uikit?

**Comment by tomhornyak** [comment]
Sorry - apparently the email went to my spam folder or was lost. I just saw this when I was going to log an unrelated issue.
created with create-next-app - react 18.2
Here is the tsconfig.json
 {
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "sourceMap": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts",
    ".next/types/app/layout.tsx"
  ],
  "exclude": ["node_modules"]
}

**Comment by ilyabrower** [comment]
Sorry for so long reply, but I still don't understand why do you have that problem... So, I can't offer a solution for it yet

**Comment by msereniti** [comment]
Closing due to long inactivity. If you still experience the bug – feel free to reopen the issue. Also, attaching reproducible example on the codesandbox will be extremely valuable.
