### ISSUE TITLE
To navigate back you have to press Esc twice

### ISSUE THREAD

**Issue by semgey** [semrush/intergalactic#998]
**Describe the bug**
When there is a link inside a tooltip, during reverse navigation via Shift + Tab, the tooltip opens again and grabs focus, which leads to navigation blocking on this element

**Code example**
Open [codesandbox](https://codesandbox.io/p/sandbox/gracious-night-m7l6lv?file=%2Fsrc%2FApp.tsx)

**To Reproduce**
1. Go to Tooltip.Popper
2. Press on Esc
3. Press Shift+Tab
4. See Tooltip.Popper again

**Expected behavior**
When you first hit the tooltip it should open, after pressing Esc it should be possible to direct the focus both forward and backward

**Comment by msereniti** [comment]
Fixed in https://github.com/semrush/intergalactic/releases/tag/v15.57.0
